---
title: "Final Project"
author: "Haorui Zhang"
date: "5/1/2019"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(rvest)
library(dplyr)
library(stringr)
```

# Part I: Data Web Scraping
```{r}
teampage <- read_html("http://www.baseball-reference.com/teams/")
fran_name <- teampage %>% html_nodes(".left") %>% html_text()
fran_name <- fran_name[2:31]
s <- html_session("http://www.baseball-reference.com/teams/")
baseball <- data.frame()
```

```{r message=FALSE}
for(i in 1:length(fran_name)) {  #length(fran_name)
  hist <- s %>% follow_link(fran_name[i]) %>% read_html()
  sub_tb <- as.data.frame(hist %>% html_nodes("#franchise_years") %>% html_table())
  sub_tb['Team'] <- fran_name[i]
  baseball <- rbind(baseball, sub_tb)
}
```

```{r}
all.equal(charToRaw(baseball$Tm[1]), charToRaw("Arizona Diamondbacks"))
```

```{r}
char_cols <- which(lapply(baseball, typeof) == "character")

for(i in char_cols){
    baseball[[i]] <- str_conv(baseball[[i]], "UTF-8")
    baseball[[i]] <- str_replace_all(baseball[[i]],"\\s"," ")
}

all.equal(charToRaw(baseball$Tm[1]), charToRaw("Arizona Diamondbacks"))
```

```{r}
dim(baseball)
```

# Part II: Data Cleaning
```{r}
# Use data from 1969-2018 because data before 1969 have different leagues from now
baseball <- baseball %>% filter(Year %in% 1969:2018)
baseball <- subset(baseball, select = -Tm)
baseball$GB[which(baseball$GB == "--")] <- 0
baseball$GB <- as.integer(baseball$GB)
```

# Part III: Exploratory Data Analysis
```{r}
plot(baseball$R, baseball$W.L.)
plot(baseball$RA, baseball$W.L.)

hist(baseball$BatAge, main = "Histogram of Batters' Average Age")
hist(baseball$PAge, main = "Histogram of Pitchers' Average Age")
```

# Part IV: Feature Engineering
```{r}
# Categorize attendance to indicate popularity
baseball$Attendance <- as.numeric(gsub("," ,"", baseball$Attendance))
# Draw histogram to decide cutoff points
hist(baseball$Attendance)

baseball$Popularity <- cut(baseball$Attendance, breaks=c(-Inf, 1000000, 2000000, 3000000, Inf),
                           labels=c("Very unpopular", "Unpopular", "Popular", "Very popular"))
baseball$Lg <- as.factor(baseball$Lg)
baseball$Popularity <- as.factor(baseball$Popularity)
baseball$W.L. <- baseball$W.L.*100
```

# Part V: Building Linear Models
```{r}
set.seed(418)
obs <- sample(1:nrow(baseball), nrow(baseball)*0.7)
train <- baseball[obs,]
test <- baseball[-obs,]

# Start with a full model
m1 <- lm(W.L. ~ Lg + GB + R + RA + Popularity + BatAge + PAge + X.Bat + X.P, data = train)
summary(m1)

# Remove insignificant predictors
m2 <- lm(W.L. ~ Lg + GB + R + RA + Popularity + PAge + X.Bat, data = train)
summary(m2)
pred <- predict(m2, subset(test, select = -W.L.))
cor(pred, test$W.L.)
```

